dev.psSleep = 5000
dev.psmSleep = 150000
dev.dfmSleep = 5000
dev.reportFtpPswd = BRIDGE9QZ
dev.jclPath = jclq
dev.authenticationHost = directory.abbott.corp
dev.authenticationBasedn = OU=Users,DC=abbott,DC=corp
dev.authenticationUserId = LDAPBIND
dev.authenticationPassword = Password1
dev.authenticationPort = 389
dev.reportNetServiceLocator = http://wa01023d.oneabbott.com:9300/p2pd/servlet/dispatch
dev.reportNetNameSpace = LDAPabbott.corp
dev.reportNetUsername = SVC-AIAP-HR_FIN_Cogn
dev.reportNetPassword = Password1
dev.reportsUrl = http://wa01023d.oneabbott.com/cognos10/cgi-bin/cognos.cgi
dev.reportNetPrinter1 = \\LAKEP03\P03LC846064
dev.reportNetPackageName = TCGM
dev.RSystemAddress = mvs.cmis.abbott.com
dev.RSystemUsername = B07RGMT
dev.RSystemPassword = CASHBOOK
dev.dbTnsName = AIFINHRQ
dev.jobPswd = tcgm
dev.oracleId = tcgm
dev.oraclePswd = tcgm
dev.crystalOdbc = TCGM
dev.datasourceURL = jdbc:oracle:oci:@AIFINHRQ.WORLD
dev.reportFtpId = TCGMFTP
dev.reportHost = AP41
dev.reportLibrary = AITCGDVFIL
dev.reportTriggerFile = TCGRPHP00
dev.reportParmFile = TCGRPPP00
dev.crystalServer = 10.236.189.94
dev.jobId = tcgm
dev.essbaseLibrary = DWDEVL
dev.essbaseHost = 10.236.189.91
dev.essbasePswd = DATAWHSEIN
dev.essbaseId = DTAWHSFTP
dev.essbaseFilename = RLTCGMDATA
dev.essbaseExportDir = \\\\aiapodiv01d\\ManageData\\EXPORTS\\ESSBASE\\

unix.dev.jclJobLogLocVal = MSGCLASS=R
unix.dev.jclUserIdVal = NOTIFY=T07PID
unix.dev.jclReadDataSetIdenVal = AB
unix.dev.jclDataSetIdenVal = DV
unix.dev.jclHostName1Val = AISHRDQA
unix.dev.jclUserPass1Val = tcgmadm 0304$Tcgm
unix.dev.jclImportsLocVal = /ManageData/IMPORTS
unix.dev.jclExportsLocVal = /ManageData/EXPORTS
unix.dev.jclHostName2Val = AP41
unix.dev.jclUserPass2Val = DTAWHSFTP DATAWHSEIN

windows.dev.jclJobLogLocVal = MSGCLASS=R
windows.dev.jclUserIdVal = NOTIFY=T07PID
windows.dev.jclReadDataSetIdenVal = AB
windows.dev.jclDataSetIdenVal = DV
windows.dev.jclHostName1Val = AIAPODIV01D
windows.dev.jclUserPass1Val = VMAS400 Vm@ap41t
windows.dev.jclImportsLocVal = \\IMPORTS
windows.dev.jclExportsLocVal = \\EXPORTS
windows.dev.jclHostName2Val = AP41
windows.dev.jclUserPass2Val = DTAWHSFTP DATAWHSEIN


qa.psSleep = 5000
qa.psmSleep = 150000
qa.dfmSleep = 5000
qa.reportFtpPswd = BRIDGE9QZ
qa.jclPath = jclq
qa.authenticationHost = directory.abbott.corp
qa.authenticationBasedn = OU=Users,DC=abbott,DC=corp
qa.authenticationUserId = LDAPBIND
qa.authenticationPassword = Password1
qa.authenticationPort = 389
qa.reportNetServiceLocator = http://wa00283q.oneabbott.com:9300/p2pd/servlet/dispatch
qa.reportNetNameSpace = LDAPabbott.corp
qa.reportNetUsername = TST-TCGM_NA1
qa.reportNetPassword = Cognos01
qa.reportsUrl = http://wa00283q.oneabbott.com/cognos10/cgi-bin/cognos.cgi
qa.reportNetPrinter1 = \\\\abtapp0076\\P03LC846064
qa.reportNetPackageName = TCGM
qa.RSystemAddress = mvs.cmis.abbott.com
qa.RSystemUsername = B07RGMT
qa.RSystemPassword = CASHBOOK
qa.dbTnsName = tcgmd
qa.jobPswd = spring-09
qa.oracleId = tcgm
qa.oraclePswd = spring-09
qa.crystalOdbc = TCGM
qa.datasourceURL = jdbc:oracle:oci:@AIFINHRQ.WORLD
qa.reportFtpId = TCGMFTP
qa.reportHost = AP41
qa.reportLibrary = AITCGDVFIL
qa.reportTriggerFile = TCGRPHP00
qa.reportParmFile = TCGRPPP00
qa.crystalServer = 10.236.189.94
qa.jobId = tcgm
qa.essbaseLibrary = DWDEVL
qa.essbaseHost = 10.236.189.91
qa.essbasePswd = DATAWHSEIN
qa.essbaseId = DTAWHSFTP
qa.essbaseFilename = RLTCGMDATA
qa.essbaseExportDir = \\\\nasap14c2001b\\aiapidiv01d$\\EXPORTS\\Essbase\\
qa.ccshost = uapd5004q.northamerica.intra.abbott.com
qa.ccsuser = ftpaiusr
qa.ccspassword = Ftp$8108
qa.ccslocation = /ora02/test/ai/usrdat/ccs
qa.ccs = AICGSPLT.WORLD
qa.ipsuser = ftpaiusr
qa.ipspassword = Ftp$8108
qa.ipslocation = /ora02/test/ai/usrdat/ips
qa.rptNetUserName=svc-tcgm-d
qa.rptNetPaswordOld=XXX
qa.rptNetPasword=XXXX
unix.qa.jclJobLogLocVal = MSGCLASS=R
unix.qa.jclUserIdVal = NOTIFY=T07PID
unix.qa.jclReadDataSetIdenVal = AB
unix.qa.jclDataSetIdenVal = DV
unix.qa.jclHostName1Val = UAPD5004q
unix.qa.jclUserPass1Val = tcgmadm Today050311
unix.qa.jclImportsLocVal = /ManageData/IMPORTS
unix.qa.jclExportsLocVal = /ManageData/EXPORTS
unix.qa.jclHostName2Val = AP41
unix.qa.jclUserPass2Val = DTAWHSFTP DATAWHSEIN

windows.qa.jclJobLogLocVal = MSGCLASS=R
windows.qa.jclUserIdVal = NOTIFY=T07PID
windows.qa.jclReadDataSetIdenVal = AB
windows.qa.jclDataSetIdenVal = DV
windows.qa.jclHostName1Val = AIAPODIV01D
windows.qa.jclUserPass1Val = VMAS400 Vm@ap41t
windows.qa.jclImportsLocVal = \\IMPORTS
windows.qa.jclExportsLocVal = \\EXPORTS
windows.qa.jclHostName2Val = AP41
windows.qa.jclUserPass2Val = DTAWHSFTP DATAWHSEIN


prod.psSleep = 5000
prod.psmSleep = 150000
prod.dfmSleep = 5000
prod.reportFtpPswd = BRIDGE9QZ
prod.jclPath = jclq
prod.authenticationHost = directory.abbott.corp
prod.authenticationBasedn = OU=Users,DC=abbott,DC=corp
prod.authenticationUserId = LDAPBIND
prod.authenticationPassword = Password1
prod.authenticationPort = 389
prod.reportNetServiceLocator = http://wa01090p.oneabbott.com:9300/p2pd/servlet/dispatch
prod.reportNetNameSpace = LDAPabbott.corp
prod.reportNetUsername = svc-tcgm
prod.reportNetPassword = Abbott123
prod.reportsUrl = http://wa01090p.oneabbott.com/cognos10/cgi-bin/cognos.cgi
prod.reportNetPrinter1 = \\\\abtapp0076\\P03LC846064
prod.reportNetPackageName = TCGM
prod.RSystemAddress = mvs.cmis.abbott.com
prod.RSystemUsername = B07RGMT
prod.RSystemPassword = CASHBOOK
prod.dbTnsName = aitcgmp.world
prod.jobPswd = tcgmprd
prod.oracleId = tcgm
prod.oraclePswd = tcgmprd
prod.crystalOdbc = TCGM
prod.datasourceURL = jdbc:oracle:oci:@AITCGMP.WORLD
prod.reportFtpId = TCGMFTP
prod.reportHost = AP41
prod.reportLibrary = AITCGDVFIL
prod.reportTriggerFile = TCGRPHP00
prod.reportParmFile = TCGRPPP00
prod.crystalServer = 10.236.189.94
prod.jobId = tcgm
prod.essbaseLibrary = DWPROD
prod.essbaseHost = 10.236.189.91
prod.essbasePswd = DATAWHSEIN
prod.essbaseId = DTAWHSFTP
prod.essbaseFilename = RLTCGMDATA
prod.essbaseExportDir = \\\\nasap14c2001b\\AIAPIDIV01$\\EXPORTS\\Essbase\\
prod.ccshost = uapd5005p.northamerica.intra.abbott.com
prod.ccsuser = ftp_ccs
prod.ccspassword = CC$ftp123
prod.ccslocation = /prod/ai/usrdat/ccs
prod.ccs = AICGSPLP
prod.ipsuser = ftp_ips
prod.ipspassword = Zo1nk$08
prod.ipslocation = /prod/ai/usrdat/ips
prod.rptNetUserName=svc-tcgm
prod.rptNetPaswordOld=XXXX
prod.rptNetPasword=XXX
unix.prod.jclJobLogLocVal = MSGCLASS=A
unix.prod.jclUserIdVal = NOTIFY=T07PID
unix.prod.jclReadDataSetIdenVal = AB
unix.prod.jclDataSetIdenVal = AB
unix.prod.jclHostName1Val = UAPD5003P
unix.prod.jclUserPass1Val = svc-tcgm n8XzrSa
unix.prod.jclImportsLocVal = /TCGMManageData/IMPORTS
unix.prod.jclExportsLocVal = /TCGMManageData/EXPORTS
unix.prod.jclHostName2Val = AP41
unix.prod.jclUserPass2Val = DTAWHSFTP DATAWHSEIN


windows.prod.jclJobLogLocVal = MSGCLASS=A
windows.prod.jclUserIdVal = NOTIFY=T07PID
windows.prod.jclReadDataSetIdenVal = AB
windows.prod.jclDataSetIdenVal = AB
windows.prod.jclHostName1Val = UAPD5003P
windows.prod.jclUserPass1Val = svc-tcgm n8XzrSa
windows.prod.jclImportsLocVal = /TCGMManageData/IMPORTS
windows.prod.jclExportsLocVal = /TCGMManageData/EXPORTS
windows.prod.jclHostName2Val = AP41
windows.prod.jclUserPass2Val = DTAWHSFTP DATAWHSEIN

windows.jclpath = jcld
unix.jclpath = jclq
prod.jclpath = jclp
