status = warn
name = TCGM
 
appender.tcgm.type = RollingFile
appender.tcgm.name = WEBAPPFILE
appender.tcgm.fileName = ${sys:catalina.home}/logs/tcgm.log
appender.tcgm.filePattern = ${sys:catalina.home}/logs/tcgm-%d{yyyy-MM-dd}-%i.log.gz
 
appender.tcgm.layout.type = PatternLayout
appender.tcgm.layout.pattern = %d [%t] %-5p - %m%n
 
appender.tcgm.policies.type = Policies
 
appender.tcgm.policies.size.type = SizeBasedTriggeringPolicy
appender.tcgm.policies.size.size = 1024KB
 
appender.tcgm.strategy.type = DefaultRolloverStrategy
appender.tcgm.strategy.max = 5
 
rootLogger.level = debug
rootLogger.appenderRefs = file
rootLogger.appenderRef.file.ref = WEBAPPFILE
 
logger.tcgm.name = abbott.ai.tcgm
logger.tcgm.level = debug
logger.tcgm.additivity = true
 
logger.commons.name = org.apache.commons
logger.commons.level = info