#It is assumed that this file sits in the WEB-INF folder

# These are the five levels of logging in log4j
#log4j.debug=true
#log4j.info=true
#log4j.warn=true
#log4j.error=true
#log4j.fatal=true

# Configure the rootlogger
log4j.appender.WEBAPP=org.apache.log4j.ConsoleAppender
log4j.appender.WEBAPP.layout=org.apache.log4j.PatternLayout
#log4j.appender.WEBAPP.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n
log4j.appender.WEBAPP.layout.ConversionPattern=%d [%t] %-5p - %m%n

# Second logger for filetrace
log4j.appender.WEBAPPFILE=org.apache.log4j.RollingFileAppender
log4j.appender.WEBAPPFILE.File=${catalina.home}/logs/tcgm.log
log4j.appender.WEBAPPFILE.MaxFileSize=1024KB
#log4j.appender.WEBAPPFILE.MaxFileSize=500KB
#log4j.appender.WEBAPPFILE.MaxBackupIndex=5
log4j.appender.WEBAPPFILE.layout=org.apache.log4j.PatternLayout
log4j.appender.WEBAPPFILE.layout.ConversionPattern=%d [%t] %-5p - %m%n

# All messages will go to console
log4j.rootLogger=debug, WEBAPPFILE

# All messages of TCGM app goes to file logger also
log4j.logger.abbott.ai.tcgm=INHERITED, WEBAPPFILE

# Here I can configger, from what loggin level I will see the traces in this case ALL
log4j.appender.WEBAPPFILE.threshold=debug

# !!!! hide some other packages
log4j.logger.org.apache.commons=info

